L2 layer typing (#2863)
* Change type of Packet.fields_desc to a Sequence

Sequences in mypy allow variance, so we can assign lists
of Field subtypes to fields_desc.

This is needed for the scapy.layers.l2.Loopback class, which
attempts to assign fields_desc twice with different types. Without this change,
we get the following mypy errors:

    scapy/layers/l2.py:620: error: Incompatible types in assignment (expression has type "List[IntEnumField]", base class "Packet" defined the type as "List[Union[Field[Any, Any], _FieldContainer]]")
    scapy/layers/l2.py:620: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
    scapy/layers/l2.py:620: note: Consider using "Sequence" instead, which is covariant

* Store just the hw address in the ARP cache in arping

The current code stores a pair of the address and the current time,
but this does not seem to match the cache's code where the time is
stored in a different field.

* Fix GRErouting.routing_info length

routing_info is a StrLenField, and accepts a lambda (now
that the fld argument was removed).

* Add type annotations to scapy.layers.l2

- Add typed attribute for Conf.neighbor in scapy.config.

  This allows mypy to acknowledge the existence of this attribute
  even though it is not initialized until the scapy.layers.l2
  module is loaded.

- Name the arp cache as a private global in layers.l2

  To avoid mypy warnings about arp_cache not being
  a member of the NetCache class, store it in its
  own variable.

- Do not accept None in ConditionalField's condition callback

  The callback is always called with a packet.

- The MACField internal representation may be None

  Modify the types and the i2repr implementation accordingly.

- Allow StrFixedLenField default argument to be None

  A None default is passed in scapy.layers.l2 for example.

- Explicitly return None in Neighbor.resolve()

- Use super() to access MACField.i2h

  When accessing the i2h method using an unbound method, mypy
  fails matching the types correctly.

- Convert a few string literals to bytes literals in scapy.layers.l2

- ShortEnumField accepts Dict[str, int] as well as Dict[int, str]

- Do not accept None in StrFixedLenField length_from callback

  The callback is almost always called with a packet, and
  most of its usage is with a lambda function that does not
  handle None. Add `type: ignore` comment to the randval method
  that does pass None to this callback (inside a try-except clause).